name: template
version: 0.1.0.2

dependencies:
  - base

library:
  exposed-modules: Template
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - template
      - hspec
