name: catalan
version: 0.1.0.2

dependencies:
  - base

library:
  exposed-modules: Catalan
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - catalan
      - hspec
